name: Analysis

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.analysis.outputs.version }}

jobs:

  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.metadata.outputs.version }}
      release: ${{ steps.metadata.outputs.release }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@v19.0.5 ${{ env.DRY_RUN }}

      - name: Set Metadata
        id: metadata
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0)
          echo "LATEST_TAG: ${LATEST_TAG}"
          
          LATEST_VERSION=$(echo "${LATEST_TAG}" | cut -c 2-)
          echo "LATEST_VERSION: ${LATEST_VERSION}"
          
          HEAD_TAGS=$(git tag --points-at HEAD)
          echo "HEAD_TAGS: ${HEAD_TAGS}"
          
          IS_HEAD_LATEST=$(echo "${HEAD_TAGS}" | grep -x "${LATEST_TAG}" | wc -l)
          echo "IS_HEAD_LATEST: ${IS_HEAD_LATEST}"
          
          [[ "${IS_HEAD_LATEST}" == "0" ]] && echo "release=false" >> $GITHUB_OUTPUT || echo "release=true" >> $GITHUB_OUTPUT
          [[ "${IS_HEAD_LATEST}" == "0" ]] && echo "version=0.0.0" >> $GITHUB_OUTPUT || echo "version=${LATEST_VERSION}" >> $GITHUB_OUTPUT
          
      - name: Read Metadata
        run: |
          echo "Version: ${{ steps.metadata.outputs.version }}"
          echo "Release: ${{ steps.metadata.outputs.release }}"
