name: Analysis

on:
  workflow_call:
    outputs:
      version:
        value: ${{ jobs.analysis.outputs.version }}

jobs:

  analysis:
    name: Analysis
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      release: ${{ steps.release.outputs.release }}
    steps:

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release@v19.0.5 ${{ env.DRY_RUN }}

      - name: Set Version
        id: version
        run: |
          VERSION=$(git describe --tags --abbrev=0 | cut -c 2-)
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Set Release
        id: release
        run: |
          TAGS=$(git tag --points-at HEAD)
          echo "${TAGS}"
          [[ "${TAGS}" == "" ]] && echo "release=false" >> $GITHUB_OUTPUT || echo "release=true" >> $GITHUB_OUTPUT

      - name: Read Metadata
        run: |
          echo "Version: ${{ steps.version.outputs.version }}"
          echo "Release: ${{ steps.release.outputs.release }}"
