name: Generate Documentation

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      solution:
        required: false
        type: string
      source:
        required: true
        type: string
    secrets:
      PACKAGES_TOKEN:
        required: false
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_DEFAULT_REGION:
        required: true
      S3_TARGET:
        required: true

jobs:

  docs:
    name: Generate Documentation
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
    steps:

      - name: Read Metadata
        run: |
          echo "Version: ${{ inputs.version }}"
          echo "Solution: ${{ inputs.solution }}"
          echo "Source: ${{ inputs.source }}"

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Add GitHub Packages as a NuGet source
        shell: bash
        run: |
          if [[ "${{ secrets.PACKAGES_TOKEN }}" == "" ]]
          then
            PASSWORD="${{ secrets.GITHUB_TOKEN }}"
            echo "Using GITHUB_TOKEN"
          else
            PASSWORD="${{ secrets.PACKAGES_TOKEN }}"
            echo "Using PACKAGES_TOKEN"
          fi

          dotnet nuget add source \
            --username StudioLE \
            --password "${PASSWORD}" \
            --store-password-in-clear-text \
            --name github "https://nuget.pkg.github.com/StudioLE/index.json"

      - name: Build Solution
        run: >
          dotnet build "${{ inputs.solution }}"
          --configuration "Release"
          -p:Version="${{ inputs.version }}"
          -p:GenerateDocumentationFile=true
          -p:ProduceReferenceAssembly=true
          -p:CopyLocalLockFileAssemblies=true
          --nologo
          --verbosity minimal

      - name: Install Illuminate.Cli
        run: |
          dotnet tool install --global Illuminate --prerelease

      - name: Create output directory
        run: mkdir -p "artifacts/${{ inputs.version }}"

      - name: Run Illuminate.Cli
        run: >
          Illuminate
          generate
          --source "${{ inputs.source }}"
          --output "artifacts/${{ inputs.version }}"

      - name: Download sections from s3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        run: >
          aws s3 cp
          s3://${{ secrets.S3_TARGET }}/_data/_Sections.yaml
          artifacts/_data/_Sections.yaml

      - name: Update sections
        run: |
          echo "  - ${{ inputs.version }}" >> artifacts/_data/_Sections.yaml
          cat artifacts/_data/_Sections.yaml

      - name: Upload Docs Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Documentation-${{ inputs.version }}
          path: artifacts
        if: ${{ always() }}
