name: Dioxus Build

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      binary_name:
        required: true
        type: string
      version:
        required: true
        type: string
      assets_repo_name:
        required: false
        type: string
      wasm_bindgen_version:
        required: false
        type: string
        default: 0.2.105
    secrets:
      assets_repo_token:
        required: false

jobs:

  build:
    name: Build
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
        # 64-bit Linux
        - target: x86_64-unknown-linux-gnu
          os: ubuntu-24.04
          test: true
        # ARM64 Linux
        - target: aarch64-unknown-linux-gnu
          os: ubuntu-24.04-arm
        # ARM64 macOS (11.0+, Big Sur+)
        - target: aarch64-apple-darwin
          os: macos-15
        # 64-bit macOS (10.12+, Sierra+)
        - target: x86_64-apple-darwin
          os: macos-15-intel
        # 64-bit Windows
        - target: x86_64-pc-windows-msvc
          os: windows-latest
        # Web Assembly
        - target: wasm32-unknown-unknown
          os: ubuntu-24.04

    steps:

    - name: Fetch dependencies
      if: contains(matrix.os, 'ubuntu')
      run: sudo apt-get update

    # https://github.com/bevyengine/bevy/blob/latest/docs/linux_dependencies.md#ubuntu
    - name: Install Ubuntu dependencies
      if: contains(matrix.os, 'ubuntu')
      run: >
        sudo apt-get install --yes
        g++
        pkg-config
        libx11-dev
        libasound2-dev
        libudev-dev
        libxkbcommon-x11-0
        libwayland-dev
        libxkbcommon-dev

    - name: Checkout Repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Restore Cargo
      id: cargo-cache
      uses: actions/cache/restore@v4
      with:
        key: cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}-${{ github.run_number }}
        restore-keys: |
          cargo-${{ matrix.target }}-${{ hashFiles('**/Cargo.lock') }}-
          cargo-${{ matrix.target }}-
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/

    - uses: actions/download-artifact@v4
      with:
        name: Cargo.toml

    - name: Add target
      run: rustup target add ${{ matrix.target }}

    - name: Cargo Build
      run: cargo build --release --target ${{ matrix.target }}

    - name: Cache Cargo
      if: always()
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.cargo-cache.outputs.cache-primary-key }}
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/

    - name: Create artifacts directory
      run: |
        rm -rf artifacts
        mkdir artifacts

    - name: Copy binary
      if: matrix.target != 'wasm32-unknown-unknown'
      run: >
        cp target/${{ matrix.target }}/release/${{ inputs.binary_name }}
        artifacts/

    - name: Checkout Assets
      if: matrix.target != 'wasm32-unknown-unknown' && inputs.assets_repo_name != ''
      uses: actions/checkout@v4
      with:
        repository: ${{ inputs.assets_repo_name }}
        token: ${{ secrets.assets_repo_token }}
        path: assets-repo
        fetch-depth: 1
        ref: assets

    - name: Copy Assets
      if: matrix.target != 'wasm32-unknown-unknown' && inputs.assets_repo_name != ''
      run: cp -r assets-repo/assets artifacts/assets

    - name: Remove Assets repo
      if: matrix.target != 'wasm32-unknown-unknown' && inputs.assets_repo_name != ''
      run: rm -rf assets-repo

    - name: Install wasm-bindgen-cli
      if: matrix.target == 'wasm32-unknown-unknown'
      run: >
        curl "https://github.com/wasm-bindgen/wasm-bindgen/releases/download/${{ inputs.wasm_bindgen_version }}/wasm-bindgen-${{ inputs.wasm_bindgen_version }}-x86_64-unknown-linux-musl.tar.gz"
        --location
        --show-error
        --silent
        | tar
        --extract
        --gzip
        --strip-components 1
        --directory "/usr/local/bin"
        --file -
        "wasm-bindgen-${{ inputs.wasm_bindgen_version }}-x86_64-unknown-linux-musl/wasm-bindgen"

    - name: Generate WebAssembly bindings
      if: matrix.target == 'wasm32-unknown-unknown'
      run: >
        wasm-bindgen --no-typescript --target web
        --out-dir web
        --out-name ${{ inputs.binary_name }}
        target/${{ matrix.target }}/release/${{ inputs.binary_name }}.wasm

    - name: Copy WebAssembly
      if: matrix.target == 'wasm32-unknown-unknown'
      run: |
        cp web/index.html artifacts/
        cp web/${{ inputs.binary_name }}.js artifacts/
        cp web/${{ inputs.binary_name }}_bg.wasm artifacts/
        cp web/style.css artifacts/

    - name: List
      if: inputs.binary_name != ''
      run: ls -R1 artifacts

    - name: Set artifact name
      id: artifact
      run: |
        ARTIFACT="${{ inputs.binary_name }}-${{ inputs.version }}-${{ matrix.target }}"
        echo "name=${ARTIFACT}" >> $GITHUB_OUTPUT

    - name: Create archive
      run: >
        tar -czvf
        ${{ steps.artifact.outputs.name }}.tar.gz
        -C artifacts
        .

    - name: Verify archive
      run: >
        tar -tzf
        ${{ steps.artifact.outputs.name }}.tar.gz

    - name: Upload archive artifact
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.artifact.outputs.name }}.tar.gz
        path: ${{ steps.artifact.outputs.name }}.tar.gz

    - name: Upload WebAssembly artifact
      uses: actions/upload-artifact@v4
      if: matrix.target == 'wasm32-unknown-unknown'
      with:
        name: WebAssembly
        path: artifacts
