name: Test

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest

env:
  CARGO_TERM_COLOR: always

jobs:

  test:
    name: Test
    runs-on: ${{ inputs.os }}
    steps:

    - name: Fetch dependencies
      run: sudo apt-get update

    - name: Install dependencies
      run: >
        sudo apt-get install
        g++
        pkg-config
        libx11-dev
        libasound2-dev
        libudev-dev
        libxkbcommon-x11-0
        libwayland-dev
        libxkbcommon-dev

    - name: Checkout Repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Restore Cargo
      id: cargo-cache
      uses: actions/cache/restore@v5
      with:
        key: cargo-${{ runner.os }}-${{ github.run_number }}
        restore-keys: cargo-${{ runner.os }}-
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/

    - name: Download Cargo Manifests
      uses: actions/download-artifact@v8
      with:
        name: cargo-manifests

    - name: Cargo Build
      run: cargo build --release --locked --workspace --features bevy/dynamic_linking

    - name: Remove Incremental Artifacts
      if: github.ref_name == 'main'
      run: rm -rf target/*/release/incremental

    - name: Prune Cargo Cache
      if: github.ref_name == 'main'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh cache list --key cargo-${{ runner.os }}- --json key --jq '.[].key' -R "${{ github.repository }}" |
        while read -r key
        do
          gh cache delete "$key" -R "${{ github.repository }}"
        done

    - name: Save Cargo Cache
      if: github.ref_name == 'main'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.cargo-cache.outputs.cache-primary-key }}
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/

    - name: Cargo Clippy
      run: |
        if ! cargo clippy --quiet --release --locked --workspace --all-targets --features bevy/dynamic_linking --message-format short 2>&1 | tee "$RUNNER_TEMP/clippy-output"
        then
          echo "::warning title=Clippy Check Failed::Please review the output for details."
          {
            echo '## cargo clippy'
            echo '```'
            cat "$RUNNER_TEMP/clippy-output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Cargo Format
      run: |
        if ! cargo fmt --check --all 2>&1 | tee "$RUNNER_TEMP/fmt-output"
        then
          echo "::warning title=Format Check Failed::Please review the output for details."
          {
            echo '## cargo fmt'
            echo '```'
            cat "$RUNNER_TEMP/fmt-output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Cargo Test
      run: cargo test --release --locked --workspace --features bevy/dynamic_linking --no-fail-fast
