name: CI/CD

on:
  workflow_call:
    inputs:
      binary_name:
        required: true
        type: string
      assets_repo_name:
        required: false
        type: string
      assets_repo_path:
        required: false
        type: string
      wasm_bindgen_version:
        required: false
        type: string
        default: 0.2.105
      web_repo_name:
        required: false
        type: string
      git_user:
        required: false
        type: string
        default: CI/CD
      git_email:
        required: false
        type: string
        default: cicd.tbxeq@passmail.com
    secrets:
      cargo_registry_token:
        required: true
      assets_repo_token:
        required: false
      web_repo_token:
        required: false
    outputs:
      version:
        value: ${{ jobs.surveyor.outputs.version }}
      environment:
        value: ${{ jobs.surveyor.outputs.environment }}
      type:
        value: ${{ jobs.surveyor.outputs.type }}

jobs:

  surveyor:
    name: Surveyor
    uses: StudioLE/Actions/.github/workflows/rust-surveyor.yml@v7

  test:
    name: Test
    uses: StudioLE/Actions/.github/workflows/bevy-test.yml@v7
    needs:
    - surveyor
    with:
      git_user: ${{ inputs.git_user }}
      git_email: ${{ inputs.git_email }}

  build:
    name: Build
    uses: StudioLE/Actions/.github/workflows/bevy-build.yml@v7
    if: needs.surveyor.outputs.version != ''
    needs:
    - surveyor
    with:
      version: ${{ needs.surveyor.outputs.version }}
      binary_name: ${{ inputs.binary_name }}
      assets_repo_name: ${{ inputs.assets_repo_name }}
      assets_repo_path: ${{ inputs.assets_repo_path }}
      wasm_bindgen_version: ${{ inputs.wasm_bindgen_version }}
    secrets:
      assets_repo_token: ${{ secrets.assets_repo_token }}

  git-tag:
    name: Tag
    if: needs.surveyor.outputs.type == 'prerelease'
    uses: StudioLE/Actions/.github/workflows/git-tag.yml@v7
    needs:
    - surveyor
    - test
    - build
    with:
      version: ${{ needs.surveyor.outputs.version }}

  github-release:
    name: Release
    if: needs.surveyor.outputs.type == 'release'
    uses: StudioLE/Actions/.github/workflows/github-release.yml@v7
    needs:
    - surveyor
    - test
    - build
    with:
      type: ${{ needs.surveyor.outputs.type }}
      version: ${{ needs.surveyor.outputs.version }}
      binary_name: ${{ inputs.binary_name }}

  cargo-publish:
    name: Cargo Publish
    if: needs.surveyor.outputs.type == 'release'
    uses: StudioLE/Actions/.github/workflows/cargo-publish.yml@v7
    needs:
    - github-release
    secrets:
      cargo_registry_token: ${{ secrets.cargo_registry_token }}

  push-webassembly:
    name: Push WebAssembly
    if: needs.surveyor.outputs.type == 'release' && inputs.web_repo_name != ''
    uses: StudioLE/Actions/.github/workflows/push-to-repo.yml@v7
    needs:
    - surveyor
    - test
    - build
    with:
      repo: ${{ inputs.web_repo_name }}
      artifact: WebAssembly
      rm: latest
      path: latest
      copy: v${{ needs.surveyor.outputs.version }}
      message: "feat: Added ${{ needs.surveyor.outputs.version }} WebAssembly build"
    secrets:
      repo_token: ${{ secrets.web_repo_token }}

