name: CI/CD

on:
  workflow_call:
    inputs:
      package_name:
        required: true
        type: string
      binary_name:
        required: false
        type: string
      run_before_test:
        required: false
        type: string
      test_args:
        required: false
        type: string
      docker_name:
        required: false
        type: string
        default: ""
      docker_args:
        required: false
        type: string
      cargo_publish:
        required: false
        type: boolean
      matrix:
        required: false
        type: string
        default: |
          [
            {
              "target": "x86_64-unknown-linux-gnu",
              "os": "ubuntu-24.04",
              "test": true
            },
            {
              "target": "x86_64-unknown-linux-musl",
              "os": "ubuntu-24.04"
            },
            {
              "target": "aarch64-unknown-linux-gnu",
              "os": "ubuntu-24.04-arm"
            },
            {
              "target": "aarch64-unknown-linux-musl",
              "os": "ubuntu-24.04-arm"
            },
            {
              "target": "aarch64-apple-darwin",
              "os": "macos-15"
            },
            {
              "target": "x86_64-apple-darwin",
              "os": "macos-15-intel"
            },
            {
              "target": "x86_64-pc-windows-msvc",
              "os": "windows-latest"
            },
            {
              "target": "aarch64-pc-windows-msvc",
              "os": "windows-11-arm"
            }
          ]
      brew_repo:
        required: false
        type: string
        default: ""
      brew_formula:
        required: false
        type: string
        default: ""
    secrets:
      cargo_registry_token:
        required: true
      docker_password:
        required: false
      brew_repo_token:
        required: false
    outputs:
      version:
        value: ${{ jobs.rust.outputs.version }}
      environment:
        value: ${{ jobs.rust.outputs.environment }}
      type:
        value: ${{ jobs.rust.outputs.type }}

jobs:

  rust:
    name: CI/CD
    uses: StudioLE/Actions/.github/workflows/ci-cd-rust.yml@v7
    with:
      package_name: ${{ inputs.package_name }}
      binary_name: ${{ inputs.binary_name }}
      run_before_test: ${{ inputs.run_before_test }}
      test_args: ${{ inputs.test_args }}
      docker_name: ${{ inputs.docker_name }}
      docker_args: ${{ inputs.docker_args }}
      cargo_publish: ${{ inputs.cargo_publish }}
      matrix: ${{ inputs.matrix }}
      brew_repo: ${{ inputs.brew_repo }}
      brew_formula: ${{ inputs.brew_formula }}
    secrets:
      cargo_registry_token: ${{ secrets.cargo_registry_token }}
      docker_password: ${{ secrets.docker_password }}
      brew_repo_token: ${{ secrets.brew_repo_token }}
