name: Dioxus Build

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      package_name:
        required: true
        type: string
      dioxus_version:
        required: true
        type: string
      artifact_name:
        required: false
        type: string
        default: WebAssembly
      version:
        required: true
        type: string
env:
  CARGO_TERM_COLOR: always

jobs:

  build:
    name: Dioxus Build
    runs-on: ${{ inputs.os }}
    steps:

    - name: Fetch dependencies
      run: sudo apt-get update

    - name: Install dependencies
      run: >
        sudo apt-get install --yes
        libwebkit2gtk-4.1-dev
        build-essential
        curl
        wget
        file
        libxdo-dev
        libssl-dev
        libayatana-appindicator3-dev
        librsvg2-dev

    - name: Checkout Repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Restore Cargo
      id: restore
      uses: actions/cache/restore@v5
      with:
        key: dioxus-${{ github.run_number }}
        restore-keys: dioxus-
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/

    - name: Download Cargo Manifests
      uses: actions/download-artifact@v8
      with:
        name: cargo-manifests

    - name: WASM target
      run: rustup target add wasm32-unknown-unknown

    - name: Install Cargo BInstall
      run: /home/linuxbrew/.linuxbrew/bin/brew install cargo-binstall

    - name: Install Dioxus CLI
      run: /home/linuxbrew/.linuxbrew/bin/cargo-binstall dioxus-cli@${{ inputs.dioxus_version }}

    - name: NPM Install
      run: npm install

    - name: Bundle for Web
      run: dx bundle --platform web

    - name: Cargo Clippy
      run: |
        if ! cargo clippy --quiet --locked --all-targets --message-format short 2>&1 | tee "$RUNNER_TEMP/clippy-output"
        then
          echo "::warning title=Clippy Check Failed::Please review the output for details."
          {
            echo '## cargo clippy'
            echo '```'
            cat "$RUNNER_TEMP/clippy-output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Cargo Format
      run: |
        if ! cargo fmt --check --all 2>&1 | tee "$RUNNER_TEMP/fmt-output"
        then
          echo "::warning title=Format Check Failed::Please review the output for details."
          {
            echo '## cargo fmt'
            echo '```'
            cat "$RUNNER_TEMP/fmt-output"
            echo '```'
          } >> "$GITHUB_STEP_SUMMARY"
        fi

    - name: Remove Incremental Artifacts
      if: github.ref_name == 'main'
      run: rm -rf target/*/release/incremental

    - name: Prune Cargo Cache
      if: github.ref_name == 'main'
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        gh cache list --key dioxus- --json key --jq '.[].key' -R "${{ github.repository }}" |
        while read -r key
        do
          gh cache delete "$key" -R "${{ github.repository }}"
        done

    - name: Save Cargo Cache
      if: github.ref_name == 'main'
      uses: actions/cache/save@v5
      with:
        key: ${{ steps.restore.outputs.cache-primary-key }}
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/

    - name: Copy bundle
      run: >
        cp -r
        target/dx/${{ inputs.package_name }}/release/web/public
        artifacts/

    - name: Set artifact name
      id: artifact
      run: |
        ARTIFACT="${{ inputs.package_name }}-${{ inputs.version }}-wasm"
        echo "name=${ARTIFACT}" >> "$GITHUB_OUTPUT"

    - name: List
      run: ls -R1 artifacts

    - name: Create archive
      run: >
        tar cJvf
        ${{ steps.artifact.outputs.name }}.tar.xz
        -C artifacts
        .

    - name: Verify archive
      run: >
        tar tvf
        ${{ steps.artifact.outputs.name }}.tar.xz

    - name: Upload archived artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ steps.artifact.outputs.name }}.tar.xz
        path: ${{ steps.artifact.outputs.name }}.tar.xz

    - name: Upload WebAssembly
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.artifact_name }}
        path: artifacts

    - name: Remove artifacts
      run: |
        rm -rf artifacts
        rm -f ${{ steps.artifact.outputs.name }}.tar.xz
