name: Docker Build
on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      version:
        required: false
        type: string
      registry:
        required: false
        type: string
        default: ghcr.io
      user:
        required: true
        type: string
      name:
        required: true
        type: string
      args:
        required: false
        type: string
    secrets:
      password:
        required: false
jobs:

  docker-build:
    name: Docker Build
    runs-on: ${{ inputs.os }}
    steps:

    - uses: actions/checkout@v4

    - name: Restore buildx
      id: buildx-cache
      uses: actions/cache/restore@v4
      with:
        path: /tmp/.buildx-cache
        key: buildx-${{ github.sha }}-${{ github.run_number }}
        restore-keys: |
          buildx-${{ github.sha }}-
          buildx-

    - name: Set Docker Image
      run: echo "DOCKER_IMAGE=${{ inputs.registry }}/${{ inputs.user }}/${{ inputs.name }}" >> $GITHUB_ENV

    - name: Login
      run: echo "$PW" | docker login ${{ inputs.registry }} -u ${{ inputs.user }} --password-stdin
      env:
        PW: ${{ secrets.password }}

    - name: Create
      run: docker buildx create --use

    - name: Build
      run: >
        docker buildx build .
        --tag $DOCKER_IMAGE:${{ github.sha }}
        --cache-from=type=local,src=/tmp/.buildx-cache
        --cache-to=type=local,dest=/tmp/.buildx-cache-new,mode=max
        --push
        ${{ inputs.args }}
      env:
        VERSION: ${{ inputs.version }}

    # Exclude unused items from buildx cache
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Clean buildx cache
      if: always()
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache

    - name: Cache buildx
      if: always()
      uses: actions/cache/save@v4
      with:
        key: ${{ steps.buildx-cache.outputs.cache-primary-key }}
        path: /tmp/.buildx-cache