name: GitHub Release

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      type:
        required: false
        type: string
        default: release
      version:
        required: true
        type: string
      notes_artifact:
        required: false
        type: string
        default: release-notes.md
      notes_file:
        required: false
        type: string
        default: release-notes.md

jobs:

  github-release:
    name: GitHub Release
    runs-on: ${{ inputs.os }}
    steps:

    - uses: actions/checkout@v4

    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.notes_artifact }}

    - name: Create Release
      if: inputs.type == 'release'
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        "v${{ inputs.version }}"
        --title "v${{ inputs.version }}"
        --notes-file "${{ inputs.notes_file }}"
        --target ${{ github.ref_name }}

    - name: Create Prerelease
      if: inputs.type == 'prerelease'
      env:
        GH_TOKEN: ${{ github.token }}
      run: >
        gh release create
        "v${{ inputs.version }}"
        --title "v${{ inputs.version }}"
        --notes-file "${{ inputs.notes_file }}"
        --target ${{ github.ref_name }}
        --prerelease