name: Push

on:
  workflow_call:
    inputs:
      os:
        required: false
        type: string
        default: ubuntu-latest
      project:
        required: false
        type: string
      version:
        required: true
        type: string
      nuget_feed:
        required: true
        type: string
      nuget_username:
        required: true
        type: string
      target_nuget_feed:
        required: true
        type: string
    secrets:
      nuget_password:
        required: true
      target_nuget_api_key:
        required: true

jobs:

  push:
    name: Push
    runs-on: ${{ inputs.os }}
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: true
      NUGET_CERT_REVOCATION_MODE: offline
      DOTNET_NUGET_SIGNATURE_VERIFICATION: false
    steps:

    - name: Checkout Repo
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        fetch-tags: true

    - name: Add NuGet Source
      if: inputs.nuget_feed != ''
      run: >
        dotnet nuget add source
        --username "${{ inputs.nuget_username }}"
        --password "${{ secrets.nuget_password }}"
        --store-password-in-clear-text
        "${{ inputs.nuget_feed }}"

    - name: Restore NuGet Dependencies
      run: >
        dotnet restore "${{ inputs.project }}"
        --nologo
        --verbosity minimal

    - name: Build
      run: >
        dotnet build "${{ inputs.project }}"
        --configuration "Release"
        -p:Version="${{ inputs.version }}"
        -p:ContinuousIntegrationBuild=true
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
        -p:IncludeSymbols=true
        -p:SymbolPackageFormat=snupkg
        --nologo
        --no-restore
        --verbosity minimal

    - name: Pack
      run: >
        dotnet pack "${{ inputs.project }}"
        --configuration "Release"
        -p:Version="${{ inputs.version }}"
        -p:ContinuousIntegrationBuild=true
        -p:PublishRepositoryUrl=true
        -p:EmbedUntrackedSources=true
        -p:IncludeSymbols=true
        -p:SymbolPackageFormat=snupkg
        --no-build
        --output artifacts/packages

    - name: List Artifacts
      run: ls -1 artifacts/packages

    - name: Push To NuGet Feed
      run: >
        dotnet nuget push "artifacts/packages/*"
        --skip-duplicate
        --source "${{ inputs.target_nuget_feed }}"
        --symbol-source "${{ inputs.target_nuget_feed }}"
        --api-key "${{ secrets.target_nuget_api_key }}"
